#!/bin/bash

export DOMAIN_NAME=${DOMAIN_NAME:-myDomain}
export ADMIN_NAME=${ADMIN_NAME:-admin}
export ADMIN_LISTEN_PORT=${ADMIN_LISTEN_PORT:-7001}
export MANAGED_SERVER_PORT=${MANAGED_SERVER_PORT:-8001}
export MANAGED_SERVER_NAME_BASE=${MANAGED_SERVER_NAME_BASE:-MS}
export CONFIGURED_MANAGED_SERVER_COUNT=${CONFIGURED_MANAGED_SERVER_COUNT:-4}
export CLUSTER_NAME=${CLUSTER_NAME:-cluster}
export PRODUCTION_MODE=${PRODUCTION_MODE:-dev}
export USERNAME=${USERNAME:-weblogic}
export PASSWORD=${PASSWORD:-weblogiC1!}
export DOMAIN_HOME=$DOMAIN_ROOT/$DOMAIN_NAME